services:
    _defaults:
        autowire: true
        autoconfigure: true

    Kabiroman\AdaptiveEntityManagerBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Resources/'
            - '../../Tests/'
            - '../../Entity/'

    Kabiroman\AdaptiveEntityManagerBundle\Service\ManagerRegistryInterface:
        alias: adaptive_entity_manager.manager_registry
        public: true
