services:
    _defaults:
        autowire: true
        autoconfigure: true

    Kabiroman\AdaptiveEntityManagerBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Resources/'
            - '../../Tests/'
            - '../../Entity/'

    # Private service for Doctrine EntityManager
#    adaptive_entity_manager.doctrine_manager:
#        synthetic: true
#        public: true

    # AdaptiveEntityManager factory
    adaptive_entity_manager.factory:
        class: Kabiroman\AdaptiveEntityManagerBundle\Service\AdaptiveEntityManagerFactory
        arguments:
            $config: '@Kabiroman\AEM\Config'
            $classMetadataProvider: '@EntityClassMetadataProvider'
            $entityDataAdapterProvider: '@Kabiroman\AEM\DataAdapter\DefaultEntityDataAdapterProvider'
            $transactionalConnection: '@?Kabiroman\AdaptiveEntityManagerBundle\Connection\DoctrineTransactionalConnection'
        public: true
        shared: true

    # Main AdaptiveEntityManager service
    adaptive_entity_manager.entity_manager:
        class: Kabiroman\AEM\AdaptiveEntityManager
        factory: ['@adaptive_entity_manager.factory', 'create']
        arguments:
            $adapterProvider: '@adaptive_entity_manager.adapter_registry'
        shared: true
        tags: ['doctrine.entity_manager']

    # Adapter registry service
    adaptive_entity_manager.adapter_registry:
        class: Kabiroman\AdaptiveEntityManagerBundle\DataAdapter\AdapterRegistry
        public: true

    # Interface alias for adapter provider
    Kabiroman\AEM\DataAdapter\EntityDataAdapterProvider:
        alias: adaptive_entity_manager.adapter_registry
        public: true

    Kabiroman\AEM\Config:
        arguments:
            $entityFolder: '%adaptive_entity_manager.entities_dir%'
            $entityNamespace: '%adaptive_entity_manager.entities_namespace%'
            $cacheFolder: '%kernel.cache_dir%'

    Kabiroman\AdaptiveEntityManagerBundle\Connection\DoctrineTransactionalConnection:
        arguments:
            $connection: '@doctrine.dbal.default_connection'  # Adjust if the constructor requires this or other arguments
        public: true
        shared: true

    Kabiroman\AdaptiveEntityManagerBundle\Metadata\BundleClassMetadataProvider:
        arguments:
            $config: '%adaptive_entity_manager.entities%'  # Inject only the entities sub-array
