services:
    _defaults:
        autowire: true
        autoconfigure: true

    Kabiroman\AdaptiveEntityManagerBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Resources/'
            - '../../Tests/'
            - '../../Entity/'

    # AdaptiveEntityManager factory
    adaptive_entity_manager.factory:
        class: Kabiroman\AdaptiveEntityManagerBundle\Service\AdaptiveEntityManagerFactory
        arguments:
            $config: '@adaptive_entity_manager.config'
            $classMetadataProvider: '@adaptive_entity_manager.entity_metadata_provider'
            $entityDataAdapterProvider: '@adaptive_entity_manager.adapter_registry'
            $transactionalConnection: '@?adaptive_entity_manager.connection'
        public: true
        shared: true

    # Main AdaptiveEntityManager service
    Kabiroman\AEM\EntityManagerInterface:
        class: Kabiroman\AEM\AdaptiveEntityManager
        factory: ['@adaptive_entity_manager.factory', 'create']
        shared: true

    # Adapter registry service
    adaptive_entity_manager.adapter_registry:
        class: Kabiroman\AdaptiveEntityManagerBundle\DataAdapter\AdapterRegistry
        public: true

    # Interface alias for adapter provider
    Kabiroman\AEM\DataAdapter\EntityDataAdapterProvider:
        alias: adaptive_entity_manager.adapter_registry
        public: true

    adaptive_entity_manager.config:
        class: Kabiroman\AEM\Config
        arguments:
            $entityFolder: '%adaptive_entity_manager.entities_dir%'
            $entityNamespace: '%adaptive_entity_manager.entities_namespace%'
            $cacheFolder: '%kernel.cache_dir%'

    adaptive_entity_manager.entity_metadata_provider:
        class: Kabiroman\AdaptiveEntityManagerBundle\Metadata\EntityClassMetadataProvider
        arguments:
            $config: '%adaptive_entity_manager.entities%'
