services:
    _defaults:
        autowire: true
        autoconfigure: true

    Kabiroman\AdaptiveEntityManagerBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Resources/'
            - '../../Tests/'
            - '../../Entity/'

    # Private service for Doctrine EntityManager
    adaptive_entity_manager.doctrine_manager:
        synthetic: true
        public: true

    # AdaptiveEntityManager factory
    adaptive_entity_manager.factory:
        class: Kabiroman\AdaptiveEntityManagerBundle\Service\AdaptiveEntityManagerFactory
        arguments:
            $entityManager: '@adaptive_entity_manager.doctrine_manager'
            $entitiesDir: '%adaptive_entity_manager.entities_dir%'
            $entitiesNamespace: '%adaptive_entity_manager.entities_namespace%'

    # Adapter registry service
    adaptive_entity_manager.adapter_registry:
        class: Kabiroman\AdaptiveEntityManagerBundle\DataAdapter\AdapterRegistry
        public: true

    # Interface alias for adapter provider
    Kabiroman\AEM\DataAdapter\EntityDataAdapterProvider:
        alias: adaptive_entity_manager.adapter_registry
        public: true
